apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: jigarzechrom/nginx-app:f07e730d12984cc133e5a523d34e18b50c1251ec
        ports:
        - containerPort: 80
